# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
# %run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)
np.show_config()

1.20.3
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [5]:
x = np.linspace(1, 100, 100)
print(x.size * x.itemsize)

800


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
x = np.zeros(10)
x[4]=1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
x = np.linspace(10, 49, 40)
x

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22.,
       23., 24., 25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35.,
       36., 37., 38., 39., 40., 41., 42., 43., 44., 45., 46., 47., 48.,
       49.])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
np.flip(x)

array([49., 48., 47., 46., 45., 44., 43., 42., 41., 40., 39., 38., 37.,
       36., 35., 34., 33., 32., 31., 30., 29., 28., 27., 26., 25., 24.,
       23., 22., 21., 20., 19., 18., 17., 16., 15., 14., 13., 12., 11.,
       10.])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
np.reshape(np.linspace(0, 8, 9), (3, 3))

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
np.nonzero([1, 2, 0, 0, 4, 0])

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
np.random.random((3, 3, 3))

array([[[0.38717501, 0.61956866, 0.9331555 ],
        [0.2799373 , 0.81809894, 0.62439599],
        [0.47654274, 0.83070857, 0.90419348]],

       [[0.55454449, 0.66846356, 0.37195829],
        [0.92471286, 0.6027341 , 0.68711904],
        [0.6949601 , 0.14840736, 0.44978353]],

       [[0.54791536, 0.83147738, 0.86147546],
        [0.72257345, 0.20938073, 0.6269783 ],
        [0.71789712, 0.3288489 , 0.4971996 ]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
x = np.random.random((10, 10))
x.min(), x.max()

(0.00500762827939627, 0.9890711871180516)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
np.mean(np.random.random((30)))

0.5501143769724012

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
x = np.ones((10, 10))
x[1:-1, 1:-1] = 0
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
x = np.random.random((4, 4))
x[:,[0,-1]]=0
x[[0,-1], :]=0
x

array([[0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.94549925, 0.96747512, 0.        ],
       [0.        , 0.01910105, 0.96603174, 0.        ],
       [0.        , 0.        , 0.        , 0.        ]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [18]:
np.diag(np.arange(1, 5),-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [19]:
x = np.zeros(9*9)
x[1::2]= 1
np.reshape(x, (9, 9))[0:8, 0:8]

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [20]:
x = np.reshape(np.linspace(1, 6*7*8, 6*7*8), (6, 7, 8))
list(map(lambda x: x[0], np.where(x==100)))

[1, 5, 3]

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [21]:
np.tile([(0, 1), (1, 0)], (4, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [22]:
x = np.random.random((5, 5))
x = (x- np.mean(x))/np.std(x)
x

array([[-0.53964189, -1.83437455, -1.18832093,  0.77294835, -0.87808128],
       [ 0.91050631,  0.78778459, -0.02761025,  0.64809857,  0.43456869],
       [-0.08287758, -0.09027164, -0.08032465,  0.79175019,  0.23787127],
       [-1.90642446, -0.31627578,  0.85781799,  1.24943275,  0.79627249],
       [-1.93241312,  0.60220154,  1.37314746,  0.9276902 , -1.51347428]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [23]:
np.dtype([("R", np.ubyte), ("G", np.ubyte), ("B", np.ubyte), ("A", np.ubyte)])

dtype([('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [24]:
x = np.random.random((5, 3))
y = np.random.random((3, 2))
x@y

array([[0.59674507, 1.08826486],
       [0.60851666, 1.06337746],
       [0.92984941, 1.54967518],
       [1.1502692 , 2.19999186],
       [1.12620117, 1.95110503]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [25]:
x = np.random.random((20))*20
x[(x>3) & (x<8)]*=-1
x

array([-6.06393699, 18.57511478, -3.36081853, 13.35017241, -6.9177607 ,
       12.58353894, 13.51844936, -5.5561355 , 13.98892116, 19.92626282,
       13.78633074, 16.12604098, -5.62042378, -4.74379543,  2.72333137,
       14.1214459 , -5.40032189, -7.30550669, -5.55516706, 17.69343283])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [26]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

In [27]:
np.array(list(map(lambda x: np.ceil(x) if x>0 else np.floor(x), np.random.uniform(-10, 10, 10))))

array([-10.,   1.,  -8.,  -9.,  -7.,  -8.,  -9.,  -9.,   1.,   7.])

#### 30. How to find common values between two arrays? (★☆☆)

In [28]:
np.intersect1d(np.array([4, 5, 6, 7, 8]), np.array([1, 2, 3, 4, 5]))

array([4, 5])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [29]:
# warnings off
a = np.seterr(all="ignore")
# warnings on
a = np.seterr(**a)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [30]:
today     = np.datetime64('today')
a_day = np.timedelta64(1)
tomorrow  = today + a_day
yesterday = today - a_day
today, tomorrow, yesterday

(numpy.datetime64('2021-08-28'),
 numpy.datetime64('2021-08-29'),
 numpy.datetime64('2021-08-27'))

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [31]:
np.arange(np.datetime64("2016-08-01"), np.datetime64("2016-09-01"), a_day)

array(['2016-08-01', '2016-08-02', '2016-08-03', '2016-08-04',
       '2016-08-05', '2016-08-06', '2016-08-07', '2016-08-08',
       '2016-08-09', '2016-08-10', '2016-08-11', '2016-08-12',
       '2016-08-13', '2016-08-14', '2016-08-15', '2016-08-16',
       '2016-08-17', '2016-08-18', '2016-08-19', '2016-08-20',
       '2016-08-21', '2016-08-22', '2016-08-23', '2016-08-24',
       '2016-08-25', '2016-08-26', '2016-08-27', '2016-08-28',
       '2016-08-29', '2016-08-30', '2016-08-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [32]:
x = np.linspace(0, 100, 51)
y = np.linspace(1, 101, 51)
np.multiply(np.add(x,y), -x/2, out=x)
x

array([-0.000e+00, -5.000e+00, -1.800e+01, -3.900e+01, -6.800e+01,
       -1.050e+02, -1.500e+02, -2.030e+02, -2.640e+02, -3.330e+02,
       -4.100e+02, -4.950e+02, -5.880e+02, -6.890e+02, -7.980e+02,
       -9.150e+02, -1.040e+03, -1.173e+03, -1.314e+03, -1.463e+03,
       -1.620e+03, -1.785e+03, -1.958e+03, -2.139e+03, -2.328e+03,
       -2.525e+03, -2.730e+03, -2.943e+03, -3.164e+03, -3.393e+03,
       -3.630e+03, -3.875e+03, -4.128e+03, -4.389e+03, -4.658e+03,
       -4.935e+03, -5.220e+03, -5.513e+03, -5.814e+03, -6.123e+03,
       -6.440e+03, -6.765e+03, -7.098e+03, -7.439e+03, -7.788e+03,
       -8.145e+03, -8.510e+03, -8.883e+03, -9.264e+03, -9.653e+03,
       -1.005e+04])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [33]:
x = np.random.random(10)*10
print(x - x%1)
print(np.floor(x))
print(np.array(list(map(lambda x: float(int(x)), x))))
print(np.trunc(x))

[9. 3. 2. 8. 4. 8. 0. 6. 5. 3.]
[9. 3. 2. 8. 4. 8. 0. 6. 5. 3.]
[9. 3. 2. 8. 4. 8. 0. 6. 5. 3.]
[9. 3. 2. 8. 4. 8. 0. 6. 5. 3.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [34]:
np.array([np.linspace(0, 4, 5)]*5)

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [35]:
np.linspace(0, 1, 11, endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [36]:
x = np.random.random(10)
x.sort()
x

array([0.0024465 , 0.07079239, 0.24214744, 0.24902936, 0.35593909,
       0.38999572, 0.48387611, 0.63227429, 0.8106045 , 0.84729164])

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [37]:
np.array_equal([1, 2, 3, 4], [1, 2, 3, 4])

True

#### 43. Make an array immutable (read-only) (★★☆)

In [38]:
x = np.random.random(10)
x.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [39]:
cartesian = np.random.random((10, 2))
np.array(list(map(lambda c: [c[0]**2 + c[1]**2, np.arctan2(c[1], c[0])], cartesian)))

array([[0.53721376, 0.52992294],
       [0.88577017, 1.20201369],
       [0.11292431, 0.36099572],
       [0.52265699, 0.94165006],
       [1.57154865, 0.82233841],
       [0.37339574, 0.14639899],
       [0.2199312 , 0.26162682],
       [1.07094137, 1.12346655],
       [0.23622481, 0.90189592],
       [0.63510641, 0.18183129]])

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [40]:
x = np.random.random(10)
x[x.argmax()] = 0
x

array([0.79094796, 0.10996167, 0.51963072, 0.1165861 , 0.64839755,
       0.5799857 , 0.08577299, 0.04299554, 0.66363411, 0.        ])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [41]:
x, y = np.meshgrid(np.linspace(0, 1, 10), np.linspace(0, 1, 10))
struct = {"X": x, "Y": y}

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [42]:
# np.set_printoptions(threshold=float("inf"))
# print(np.random.random((10, 10)))

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [52]:
x = np.random.random(10)*10
scalar = 3
x[np.abs(x - scalar).argmin()]

3.184907135374809

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)